### ISSUE TITLE
[Lógica][Front][App] Completar Meta

### ISSUE THREAD

**Issue by Felipele17** [Felipele17/Macro#157]
> Como usuário quero visualizar meu Card de Meta me indicando estar finalizado para compreender que não se trata mais de uma prioridade para mim.

Pré Requisito:
 - Card de Meta
 - Asset de Meta concluída

Tasks:
 - [x] Alterar tela para novo Asset e nova cor de Card ao estar com gráfico concluído
 - [x] Tratar gráfico de Card ao estar em 100% para não ultrapassar o seu espaço delimitado
 - [ ] Garantir com que o Card completado vá para o final da lista

Quanto tempo vai demorar: 2 dias

Observação:
